"use strict";

{

    let locationArray = ["Mississippi", "Ney York", "Florida", "Texas", "Nevada"];
    let randomLocation = locationArray[Math.floor(Math.random()*locationArray.length)];
    return randomLocation;
}

{

    let restaurantArray = ["Rasin Canes", "Taco Bell", "Wendy's", "Burger King", "Arby's"];
    let randomRestaurant = restaurantArray[Math.floor(Math.random()*restaurantArray.length)];
    return randomRestaurant;
}


{

    let transporationArray = ["Car", "Plane", "Bluehound"];
    let randomTransportation = transporationArray[Math.floor(Math.random()*transporationArray.length)];
    return randomTransportation;
}
{

    let entertainmentArray = ["Hiking", "Mall", "City Tour", "Museum", "Casino"];
    let randomEntertainment = entertainmentArray[Math.floor(Math.random()*entertainmentArray.length)];
    return randomEntertainment;
}
