"use strict";

function destination(){

    let locationArr = ["Mississippi", "Ney York", "Florida", "Texas", "Nevada"];
    let randomLocation = locationArr[Math.floor(Math.random()*locationArr.length)];
        return randomLocation;
}

function destination(){

    let restaurantArr = ["Rasin Canes", "Taco Bell", "Wendy's", "Burger King", "Arby's"];
    let randomRestaurant = restaurantArray[Math.floor(Math.random()*restaurantArr.length)];
        return randomRestaurant;
}


function destination(){

    let transporationArr = ["Car", "Plane", "Bluehound"];
    let randomTransportation = transporationArr[Math.floor(Math.random()*transporationArr.length)];
        return randomTransportation;
}


function destination(){

    let entertainmentArr = ["Hiking", "Mall", "City Tour", "Museum", "Casino"];
    let randomEntertainment = entertainmentArr[Math.floor(Math.random()*entertainmentArr.length)];
        return randomEntertainment;
}
